Feature/treeview
kalidea/kaligraphi pull request #104
Opened 2018-12-07 17:03 UTC by ydomenjoud

2018-12-08 11:16 UTC, jsp-up requested changes

2018-12-08 11:16 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-tree/kal-tree.component.ts
> +    console.log($event);
emit event on drop ?

2018-12-08 17:47 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-tree/kal-tree.component.ts
> +    console.log($event);
This PR is  a proof of concept for michael.not a real PR.

2018-12-14 15:44 UTC, jsp-up approved these changes

2018-12-14 15:51 UTC, merged

2018-12-14 15:53 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-tree/components/kal-tree-node.component.ts
> +  set kalNestedTreeNode(node) {
type node

2018-12-14 15:53 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-tree/components/kal-tree-node.component.ts
> +  node: T;
format code

2018-12-14 16:01 UTC, MichaelGrosio commented on src/app/atoms/atoms.module.ts
>  import { SnackbarComponent } from './snackbar/snackbar.component';
format code

2018-12-14 16:01 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-tree/classes/kal-tree-control.ts
> +export class KalTreeControl extends NestedTreeControl<KalTreeNode> {
Why did you make a kalTreeControl, you can use NestedTreeControl !