convert nested tree to flat tree
kalidea/kaligraphi pull request #117
Opened 2018-12-21 14:51 UTC by ydomenjoud

2019-01-04 08:25 UTC, jsp-up requested changes

2019-01-04 08:25 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-tree/components/kal-tree-node.component.ts
> +  template: '<ng-content ></ng-content>',
remove space

2019-01-04 08:25 UTC, jsp-up commented on src/app/atoms/tree/tree.component.html
> +      {{node.title}} qsqsd
qsqsd

2019-01-04 08:25 UTC, jsp-up commented on src/app/atoms/tree/tree.component.ts
> +    console.log($event);
console.log

2019-01-04 08:55 UTC, ydomenjoud commented on src/app/atoms/tree/tree.component.ts
> +    console.log($event);
Not an issue in playground

2019-01-07 10:04 UTC, jsp-up approved these changes

2019-01-07 10:24 UTC, merged