Fix datepikcer
kalidea/kaligraphi pull request #119
Opened 2019-01-03 15:24 UTC by jsp-up

2019-01-04 06:32 UTC, ydomenjoud requested changes
Add unit tests to check this fix.

2019-01-07 10:18 UTC, ydomenjoud approved these changes

2019-01-07 10:19 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/package.json
> +  "version": "0.0.54",
why ?

2019-01-07 10:19 UTC, ydomenjoud requested changes
why did you update version ?

2019-01-07 11:05 UTC, jsp-up commented on projects/kalidea/kaligraphi/package.json
> +  "version": "0.0.54",
It wasan error

2019-01-07 11:42 UTC, ydomenjoud approved these changes

2019-01-07 11:43 UTC, merged