Feature/kal tab panel
kalidea/kaligraphi pull request #12
Opened 2018-10-25 15:08 UTC by MichaelGrosio

2018-10-26 07:20 UTC, Bellico commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-tabs/README.md
> +* Doit afficher les onglets en fonction du ng-content
French?

2018-10-26 07:20 UTC, Bellico commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-tabs/kal-tab-group/kal-tab-group.component.ts
> +  contentTemplatePortal: TemplatePortal;
is it useful ?

2018-10-26 07:20 UTC, Bellico commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-tabs/kal-tab-group/kal-tab-group.component.html
> +  <h1>HEADER</h1>
Is it the final render?

2018-10-26 07:20 UTC, Bellico commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-tabs/kal-tab-group/kal-tab-group.component.html
> +                class="test"
Test here ?

2018-10-29 12:41 UTC, jsp-up requested changes

2018-10-29 12:41 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-tabs/kal-tab-body/kal-tab-body.component.ts
> +  ngOnInit() {
remove

2018-10-29 12:41 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-tabs/kal-tab-group/kal-tab-group.component.ts
> +  ngOnInit() {
remove

2018-10-29 12:41 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-tabs/kal-tab-header/kal-tab-header.component.ts
> +  @Input() label = '';
getter and setter ?

2018-10-29 12:41 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-tabs/kal-tab-header/kal-tab-header.component.ts
> +  ngOnInit() {
remove

2018-10-29 12:41 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-tabs/kal-tab/kal-tab.component.ts
> +  @Input() label = '';
getter and setter ?

2018-10-29 12:41 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-tabs/kal-tab/kal-tab.component.ts
> +  constructor() {
remove

2018-10-29 12:41 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-tabs/kal-tab/kal-tab.component.ts
> +  ngOnInit() {
remove

2018-10-29 14:58 UTC, jsp-up approved these changes

2018-10-29 14:59 UTC, merged