Close issue #131
kalidea/kaligraphi pull request #132
Opened 2019-01-24 15:59 UTC by jsp-up

2019-01-25 07:57 UTC, ydomenjoud requested changes

2019-01-25 07:57 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-slider/kal-slider.component.spec.ts
> +      fixture.detectChanges();
why call detectChanges ? You don't check component vue in this test

2019-01-25 07:57 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-slider/kal-slider.component.ts
> +    if (this.value < this.min) {
refactor to avoid duplication logic

2019-01-25 07:57 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-slider/kal-slider.component.ts
> +    if (this.value > this.max) {
refactor to avoid duplication logic

2019-01-30 08:45 UTC, jsp-up commented
The PR is out to date because of the new slider.

2019-01-30 08:45 UTC, closed without merging