fix slider issues
kalidea/kaligraphi pull request #135
Opened 2019-01-29 16:44 UTC by ydomenjoud

fix slider issue :
manage @input from and coerce input

2019-01-29 17:49 UTC, jsp-up requested changes

2019-01-29 17:49 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-slider/kal-slider.component.sass
> +        cursor: grab
Grab cursor has no compatibility with IE

2019-01-29 19:38 UTC, MichaelGrosio approved these changes

2019-01-30 08:05 UTC, jsp-up approved these changes

2019-01-30 08:05 UTC, merged