Update kal selection
kalidea/kaligraphi pull request #150
Opened 2019-02-14 11:13 UTC by MichaelGrosio

2019-02-14 13:05 UTC, jsp-up requested changes

2019-02-14 13:05 UTC, jsp-up commented on projects/kalidea/kaligraphi/package.json
> +    "lodash": "latest",
sure about that ?

2019-02-14 13:05 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-list/kal-list.component.ts
> +    // this._selection = new KalListSelection<T>();
comment

2019-02-14 13:05 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-list/kal-list.component.ts
> +  isHighlighted(item) {
type returns

2019-02-14 13:05 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-list/kal-selection.ts
> +  count ? = 0; // Total of elements
Is the editor able to define theses properties with its comment ?
Maybe you should set comments with /** */

2019-02-14 13:05 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-list/kal-selection.ts
> +class SubSelectionModel<T extends { id?: string }> extends SelectionModel<T> {
This class is only used in Kaligraphi ?

2019-02-14 13:05 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-list/kal-selection.ts
> +  get total() {
type returns

2019-02-14 13:05 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-list/kal-selection.ts
> +  changes() {
empty function

2019-02-14 14:33 UTC, ydomenjoud submitted a review, later dismissed

2019-02-14 14:37 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-list/kal-list.component.ts
>          (items: T[]) => {
factorize subscribe

2019-02-15 10:57 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-list/kal-selection.ts
> +class SubSelectionModel<T extends { id?: string }> extends SelectionModel<T> {
Yes

2019-02-15 12:55 UTC, jsp-up submitted a review, later dismissed

2019-02-15 13:51 UTC, jsp-up approved these changes

2019-02-15 13:51 UTC, merged