Fix/kal select
kalidea/kaligraphi pull request #26
Opened 2018-11-07 11:23 UTC by Bellico

2018-11-07 14:19 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-select/kal-select.component.ts
> +  select(value: any, notify = false): void {
could you explain where you need this feature ?

2018-11-07 14:19 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-select/kal-select.component.ts
> +  private optionSelected(option: KalOptionComponent, withNotify: boolean = true) {
consistency : you should use same parameters name for same action

2018-11-07 14:47 UTC, MichaelGrosio requested changes

2018-11-07 14:47 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-option/kal-option.component.html
> +     [class.highlight]="isHighlighted"
kal-option-highlighted

2018-11-07 14:47 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-option/kal-option.component.html
>       [class.disabled]="disabled">
kal-option-disabled

2018-11-07 14:47 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-option/kal-option.component.html
>       [class.active]="active"
kal-option-active

2018-11-07 14:47 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-select/kal-select.component.ts
> +  private optionSelected(option: KalOptionComponent, withNotify: boolean = true) {
you can just set a value, typescript will type the parameter automatically

2018-11-07 20:26 UTC, Bellico commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-select/kal-select.component.ts
> +  select(value: any, notify = false): void {
select method is call on writevalue method, at this moment we should not notify the control

2018-11-08 15:36 UTC, MichaelGrosio submitted a review, later dismissed

2018-11-08 15:56 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-select/kal-select.component.ts
>      this.valueChange.emit(this.selectedValue);
should be in withNotify block

2018-11-08 16:06 UTC, ydomenjoud approved these changes

2018-11-08 16:06 UTC, merged