Enhancement/kal datepicker/replace luxon by dayjs
kalidea/kaligraphi pull request #260
Opened 2019-11-19 14:47 UTC by jsp-up

2019-11-19 14:54 UTC, jsp-up commented
Close #231

2019-11-20 08:34 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-datepicker/kal-date.ts
> +            exlusions = {start: false, end: false}): boolean {
ex**c**lusion , with a `c`

2019-11-20 08:34 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-datepicker/kal-datepicker.component.ts
> +dayjs.extend(localeData);
already present in kal-month-calendar.component.ts

2019-11-20 08:34 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-datepicker/kal-month-calendar/kal-month-calendar.component.ts
> +dayjs.extend(localeData);
already present in kal-datepicker.component.ts

2019-11-20 08:34 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-datepicker/kal-month-calendar/kal-month-calendar.component.ts
> +    const days: string[] = dayjs().localeData().weekdaysMin().map(day => capitalize(day).charAt(0));
day.chartAt(0).toUpperCase() , no need for capitalize

2019-11-21 14:49 UTC, MichaelGrosio requested changes

2019-11-21 14:49 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/utils/helpers/arrays.ts
> +export function move(array: any[], moveIndex: number, toIndex: number) {
function move(array: string[], start: number, end: number) {
    const startElement = array.splice(start, 1);
    array.splice(end, 0, ...startElement);
    return array;
}

2019-11-21 14:49 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-datepicker/kal-month-calendar/kal-month-calendar.component.ts
> +  updateDate(dateUnit: DateUnits) {
you just use value {value}: DateUnits

2019-11-21 14:59 UTC, ydomenjoud approved these changes

2019-11-21 15:02 UTC, MichaelGrosio approved these changes

2019-11-21 15:11 UTC, merged