Fix height of virtual scroll in kal-list
kalidea/kaligraphi pull request #261
Opened 2019-12-04 10:00 UTC by MichaelGrosio

2019-12-09 09:55 UTC, ydomenjoud requested changes

2019-12-09 09:55 UTC, ydomenjoud commented on src/app/03-layout/list/list.component.ts
> +            if (value.end >= this.displayedElement && this.cachedData.length <= this.total.getValue()) {
indent

2019-12-18 10:56 UTC, jsp-up approved these changes

2020-01-10 14:31 UTC, ydomenjoud approved these changes

2020-01-10 14:57 UTC, merged