#266
kalidea/kaligraphi pull request #267
Opened 2019-12-11 10:07 UTC by coco33300

2019-12-13 14:29 UTC, MichaelGrosio requested changes

2019-12-13 14:29 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-datepicker/kal-datepicker.component.ts
> +    this.control = this.createControlAndSubscriptions(this.injector, 'change');
add blur

2019-12-13 14:29 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-datepicker/kal-datepicker.component.ts
> +    if (this.isOpen) {
use overlayRef

2019-12-18 08:32 UTC, ydomenjoud approved these changes

2019-12-19 09:25 UTC, MichaelGrosio approved these changes

2019-12-19 09:25 UTC, merged