Add a placeholder directive for multiple selection in kal-select
kalidea/kaligraphi pull request #293
Opened 2020-05-28 21:18 UTC by MichaelGrosio

2020-06-02 07:52 UTC, coco33300 submitted a review, later dismissed

2020-06-03 07:42 UTC, ydomenjoud requested changes

2020-06-03 07:42 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-select/kal-select-multiple-placeholder.directive.ts
> +export class KalSelectMultiplePlaceholderDirective {
why did you call it "multiple" ? "KalSelectPlaceholder" is a better match ?

2020-06-03 07:42 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-select/kal-select.component.ts
> +    if (this.multiple) {
placeholder should be set despite multiple parameter

2020-06-03 13:43 UTC, ydomenjoud approved these changes

2020-06-03 13:44 UTC, merged