replace dayjs with luxon
kalidea/kaligraphi pull request #344
Opened 2021-01-12 16:04 UTC by ydomenjoud

this is a POC, do not merge

2021-02-01 10:35 UTC, MichaelGrosio requested changes

2021-02-01 10:35 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-datepicker/kal-datepicker.component.ts
> +      return KalDate.now().year + this.yearsIncrement;
Tu peux utiliser new KalDate().year

2021-02-01 10:35 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-datepicker/kal-datepicker.component.ts
> +      .subscribe(() => this.open());
Utilise un tap pour cet observable

2021-02-01 10:36 UTC, coco33300 commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-datepicker/kal-datepicker.component.ts
> +  @Input() format: KalDateFormat;
Cette input semble ne pas être utilisée

2021-02-01 10:47 UTC, MichaelGrosio requested changes

2021-02-01 10:47 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/99-utility/kal-date/kal-date.ts
> +    return this.value && this.value.isValid;
return this.value?.isValid;

2021-02-01 10:47 UTC, MichaelGrosio commented on projects/kalidea/kaligraphi/src/lib/99-utility/kal-date/kal-date.ts
> +    return this.isSame(KalDate.now());
Tu peux utiliser un new KalDate()

2021-02-19 14:17 UTC, MichaelGrosio approved these changes

2021-02-19 14:26 UTC, merged