Feature/kal button
kalidea/kaligraphi pull request #39
Opened 2018-11-14 09:11 UTC by KALjpo

2018-11-14 09:21 UTC, ydomenjoud requested changes

2018-11-14 09:21 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-button/kal-button.component.sass
> +    &.#{$self}--primary
same as `&--primary`

2018-11-14 09:21 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-button/kal-button.component.sass
> +      +kal-themed-button(get('form.elements.button.primary', $kal-parameters))
should use @each : 
```sass
@each $key, $params in get('form.elements.button.variantes', $kal-parameters)
  &--#{$key}
    +kal-themed-button($params)
```

2018-11-14 09:21 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-button/kal-button.component.sass
> +    &.#{$self}--reverse
add reverse in kal-themed-button mixin

2018-11-14 09:21 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-menu/kal-menu.component.html
> +  width="150px"
image should be 100% width and liimted in main project using library

2018-11-14 09:21 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-menu/kal-menu.component.html
> +  height="150px"/>
do not provide height, for auto scalling

2018-11-14 09:21 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/styles/_parameters.scss
> +  'primary': (
put all themes in sub key `variantes` or `themes`

2018-11-14 09:21 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/styles/_parameters.scss
> +  'reverse': (
put each reverse in related variante

2018-11-14 09:21 UTC, ydomenjoud commented on src/app/molecules/button/button.component.html
> +<h1>kal-button</h1>
provide tool to edit theme of this button on the fly

2018-11-14 09:39 UTC, KALjpo commented on projects/kalidea/kaligraphi/src/lib/molecules/kal-button/kal-button.component.sass
> +    &.#{$self}--primary
non, car du coup
**kal-button--primary button** est moins fort que ### kal-button button
il faut###  kal-button.kal-button--primary button

2018-11-15 10:29 UTC, ydomenjoud approved these changes

2018-11-15 10:29 UTC, merged