Feature/progress bar
kalidea/kaligraphi pull request #4
Opened 2018-10-22 09:42 UTC by jsp-up

2018-10-25 13:19 UTC, Bellico submitted a review, later dismissed

2018-10-25 14:23 UTC, ydomenjoud requested changes
fix comments

2018-10-25 14:23 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-progress-bar/kal-progress-bar.component.ts
> +  }
trigger detection changes on new value

2018-10-25 14:23 UTC, ydomenjoud commented on src/app/atoms/progress-bar/progress-bar.component.html
> +       type="text"
type="color"

2018-10-25 14:31 UTC, jsp-up commented on projects/kalidea/kaligraphi/src/lib/atoms/kal-progress-bar/kal-progress-bar.component.ts
> +  }
Already did that in onChanges

2018-10-29 10:48 UTC, ydomenjoud approved these changes

2018-10-29 10:49 UTC, merged