Releases/v15.2.8
kalidea/kaligraphi pull request #400
Opened 2023-05-03 13:08 UTC by eliferd

- Fixed deprecated `Injector` instances (basicaly `PortalInjector`).

2023-05-03 13:21 UTC, coco33300 approved these changes
J'ai pas relu tout les changements pour la transition mais ça me semble bon

2023-05-23 09:45 UTC, MichaelGrosio approved these changes

2023-05-23 09:46 UTC, merged

2023-05-23 12:40 UTC, ydomenjoud requested changes

2023-05-23 12:40 UTC, ydomenjoud commented on projects/kalidea/kaligraphi/src/lib/02-form/kal-select/kal-select.component.ts
> +  static readonly overlayClassName = INFORMATION_BASE_CLASS_NAME + 'overlay';
pas forcément utile, c'est pareil qu'avant

2023-05-23 12:40 UTC, ydomenjoud commented on tsconfig.json
> +    "target": "ES2022",
pourquoi changer la target ? ES2022, c'est pas forcément supporté à fond par tous les browsers .

La target c'est "dans quelle version sera transpilé le Typescript que vous avez écrit". Si tu mets trop haut, tu vas avoir des browsers qui supportent pas encore cette version. 

Si tu as besoin de fonctionnalité en plus lors de ton dev, il faut plutôt rajouter dans "lib" que dans "target"

2023-05-23 12:40 UTC, ydomenjoud commented on tsconfig.json
> +    "useDefineForClassFields": false
attention a ce paramètre, qui induit un gros changement dans comment le code s'éxecute.

De plus, quand la target est ES2020 ( ou plus haut ) , il passe automatiquement à true.

Je pense que tu as mis ça car tu as changé la target. peut être remettre la target sur une version ES2020 ( ça me semble un peu haut tout de même, mais bon si ça marchait jusqu'à maintenant ... )